### ISSUE TITLE
Can not dynamically add shaders from code

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-fundamental#58]
I attempted to dynamically add a shader from code and I got an error.

http://runstant.com/cx20/projects/ff46f0e3
```
gr(function() {
    var $$ = gr('#canvas');
    $$('goml').addComponent('import-material', {typeName:'colorShader', src:ASSETS['index.sort']});
    $$('scene').addComponent('mesh', {material:"new(colorShader)", geometry:"c1"});
    $$('mesh').addComponent('Rotate');
});
```

```
grimoire-preset-basic.js:33474 
Error: component 'import-material|HTTP://GRIMOIRE.GL/NS/DEFAULT' is not defined.
    at GomlNode.addComponent (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:30265:23)
    at https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:31332:22
    at https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:31254:21
    at Array.forEach (native)
    at https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:31253:23
    at Array.forEach (native)
    at NodeInterface.forEach (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:31252:24)
    at NodeInterface.addComponent (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:31331:18)
    at http://static.runstant.com/cx20/projects/ff46f0e3/full:104:16
    at https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:31933:37
```

**Comment by cx20** [comment]
It seems to use addChildByName instead of addComponent when adding nodes.
```
gr(function() {
    var $$ = gr('#canvas');
    $$('goml').addChildByName('import-material', {typeName:'colorShader', src:ASSETS['index.sort']});
    $$('scene').addChildByName('mesh', {material:"new(colorShader)", geometry:"c1"});
    $$('mesh').addComponent('Rotate');
});
```

**Comment by cx20** [comment]
This Issue has been solved so I will close it.

http://jsdo.it/cx20/6NnU
